fb_api/authentication/routes.py
from flask import Blueprint, render_template, request, redirect, flash
from flask.helpers import url_for
from fb_api.forms import UserLoginForm
from fb_api.models import db, User, check_password_hash
from werkzeug.security import generate_password_hash

from flask_login import login_user, logout_user, login_required


auth = Blueprint('auth', __name__, template_folder='auth_templates')

@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        existing_user = User.query.filter_by(email=form.email.data).first()
        if existing_user is None:
            email = form.email.data
            password = form.password.data
            print(email, password)
            new_user = User(email, password)
            db.session.add(new_user)
            db.session.commit()
            flash(f'Your email account ({email}) has been successfully created!', 'create-success')
            return redirect(url_for('auth.signin'))
        flash(f'A user already exists with that email address, please try again', 'auth-nogood')
    elif request.method == 'POST' and form.validate_on_submit() == False:
        flash(f'Please enter a valid email', 'auth-fail')
    return render_template('signup.html', form = form)

@auth.route('/signin', methods=['GET','POST'])
def signin():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        print(email, password)
        logged_user = User.query.filter(User.email == email).first()
        if logged_user and check_password_hash(logged_user.password, password):
            login_user(logged_user)
            flash(f'You are now logged in as {email}', 'auth-success')
            return redirect(url_for('site.home'))
        else:
            flash(f'Incorrect email/password, please try again.', 'auth-fail')
            return redirect(url_for('auth.signin'))
    elif request.method == 'POST' and form.validate_on_submit() == False:
        flash(f'Please enter a valid email', 'auth-fail')
    return render_template('signin.html', form = form)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    flash(f'You have successfully logged out.', 'auth-success')
    return redirect(url_for('site.home'))

fb_api/site/routes.py
from flask import Blueprint, render_template
from flask.app import Flask
import requests
import http.client
from flask import Response
from flask import request
from flask.json import jsonify
import json

from dotenv import load_dotenv
import os
from datetime import datetime

def configure():
    load_dotenv()



site = Blueprint('site', __name__, template_folder='site_templates')


headers = {
    'x-rapidapi-host': "v3.football.api-sports.io",
    'x-rapidapi-key':os.getenv('api_key')
    }


@site.route('/fixtures', methods=['GET','POST'])
def fixtures():
    configure()
    if request.method == 'POST':
        if request.form['submit_button'] == 'Get EPL Fixtures':
            
            url = "https://v3.football.api-sports.io/fixtures?next=10&league=39&season=2022"

            payload={}


            response = requests.request("GET", url, headers=headers, data=payload)

            data = response.json()['response']
            
            date_obj = data['fixtures']['date']
            new_date = datetime.strptime(date_obj, '%Y-%m-%dT%H:%M:%S').strftime('%Y-%m-%d')

            return render_template("fixtures.html", data=data, new_date=new_date)

        if request.form['submit_button'] == 'Get La Liga Fixtures':
            
            url = "https://v3.football.api-sports.io/fixtures?next=10&league=140&season=2022"

            payload={}


            response = requests.request("GET", url, headers=headers, data=payload)
            
            data = response.json()['response']
            
            return render_template("fixtures.html", data=data)

        if request.form['submit_button'] == 'Get Bundesliga Fixtures':
            
            url = "https://v3.football.api-sports.io/fixtures?next=10&league=78&season=2022"

            payload={}


            response = requests.request("GET", url, headers=headers, data=payload)
            
            data = response.json()['response']
            
            return render_template("fixtures.html", data=data)

        if request.form['submit_button'] == 'Get Serie A Fixtures':
            
            url = "https://v3.football.api-sports.io/fixtures?next=10&league=135&season=2022"

            payload={}


            response = requests.request("GET", url, headers=headers, data=payload)
            
            data = response.json()['response']
            
            return render_template("fixtures.html", data=data)


        if request.form['submit_button'] == 'Get French Division 1 Fixtures':
            
            url = "https://v3.football.api-sports.io/fixtures?next=10&league=61&season=2022"

            payload={}


            response = requests.request("GET", url, headers=headers, data=payload)
            
            data = response.json()['response']
            
            return render_template("fixtures.html", data=data)

        if request.form['submit_button'] == 'Get MLS Fixtures':
            
            url = "https://v3.football.api-sports.io/fixtures?next=10&league=253&season=2022"

            payload={}


            response = requests.request("GET", url, headers=headers, data=payload)
            
            data = response.json()['response']
            
            return render_template("fixtures.html", data=data)
    return render_template('fixtures.html')


@site.route('/standings', methods=['GET','POST'])
def standings():
    configure()
    if request.method == 'POST':
        if request.form['submit_button'] == 'Get EPL Standings':
         
            url = "https://v3.football.api-sports.io/standings?league=39&season=2022"

            payload={}


            response = requests.request("GET", url, headers=headers, data=payload)
            data = response.json()['response'][0]['league']['standings'][0] 
            return render_template("standings.html", data=data)

    
        if request.form['submit_button'] == 'Get La Liga Standings':
         
            url = "https://v3.football.api-sports.io/standings?league=140&season=2022"

            payload={}


            response = requests.request("GET", url, headers=headers, data=payload)
            data = response.json()['response'][0]['league']['standings'][0] 
            return render_template("standings.html", data=data)
    

        if request.form['submit_button'] == 'Get Bundesliga Standings':
         
            url = "https://v3.football.api-sports.io/standings?league=78&season=2022"

            payload={}


            response = requests.request("GET", url, headers=headers, data=payload)
            data = response.json()['response'][0]['league']['standings'][0] 
            return render_template("standings.html", data=data)

        if request.form['submit_button'] == 'Get MLS Standings':
         
            url = "https://v3.football.api-sports.io/standings?league=253&season=2022"

            payload={}


            response = requests.request("GET", url, headers=headers, data=payload)
            data = response.json()['response'][0]['league']['standings'][0] 
            return render_template("standings.html", data=data)

        if request.form['submit_button'] == 'Get Serie A Standings':
         
            url = "https://v3.football.api-sports.io/standings?league=135&season=2022"

            payload={}


            response = requests.request("GET", url, headers=headers, data=payload)
            data = response.json()['response'][0]['league']['standings'][0] 
            return render_template("standings.html", data=data)

        if request.form['submit_button'] == 'Get French Division 1 Standings':
         
            url = "https://v3.football.api-sports.io/standings?league=61&season=2022"

            payload={}


            response = requests.request("GET", url, headers=headers, data=payload)
            data = response.json()['response'][0]['league']['standings'][0] 
            return render_template("standings.html", data=data)
        
    return render_template("standings.html")

@site.route('/')
def home():
    return render_template('index.html')


@site.route('/scorers', methods=['GET','POST'])
def scorers():
    configure()
    if request.method == 'POST':
        if request.form['submit_button'] == 'EPL Top Scorers':
            
            url = "https://v3.football.api-sports.io/players/topscorers?league=39&season=2022"

            payload={}


            response = requests.request("GET", url, headers=headers, data=payload)
            
            data = response.json()['response']
            
            return render_template("scorers.html", data=data)

        if request.form['submit_button'] == 'La Liga Top Scorers':
            
            url = "https://v3.football.api-sports.io/players/topscorers?league=140&season=2022"

            payload={}


            response = requests.request("GET", url, headers=headers, data=payload)
            
            data = response.json()['response']
            
            return render_template("scorers.html", data=data)

        if request.form['submit_button'] == 'Bundesliga Top Scorers':
            
            url = "https://v3.football.api-sports.io/players/topscorers?league=78&season=2022"

            payload={}


            response = requests.request("GET", url, headers=headers, data=payload)
            
            data = response.json()['response']
            
            return render_template("scorers.html", data=data)

        if request.form['submit_button'] == 'Serie A Top Scorers':
            
            url = "https://v3.football.api-sports.io/players/topscorers?league=135&season=2022"

            payload={}


            response = requests.request("GET", url, headers=headers, data=payload)
            
            data = response.json()['response']
            
            return render_template("scorers.html", data=data)

        if request.form['submit_button'] == 'French Division 1 Top Scorers':
            
            url = "https://v3.football.api-sports.io/players/topscorers?league=61&season=2022"

            payload={}


            response = requests.request("GET", url, headers=headers, data=payload)
            
            data = response.json()['response']
            
            return render_template("scorers.html", data=data)

        if request.form['submit_button'] == 'MLS Top Scorers':
            
            url = "https://v3.football.api-sports.io/players/topscorers?league=253&season=2022"

            payload={}


            response = requests.request("GET", url, headers=headers, data=payload)
            
            data = response.json()['response']
            
            return render_template("scorers.html", data=data)
    return render_template('scorers.html')

@site.route('/profile')
def profile():
    return render_template('profile.html')

@site.route('/assists', methods=['GET','POST'])
def assists():
    configure()
    if request.method == 'POST':
        if request.form['submit_button'] == 'EPL Playmakers':
            
            url = "https://v3.football.api-sports.io/players/topassists?season=2022&league=39"

            payload={}


            response = requests.request("GET", url, headers=headers, data=payload)
            
            data = response.json()['response']
            
            return render_template("assists.html", data=data)

        if request.form['submit_button'] == 'La Liga Playmakers':
            
            url = "https://v3.football.api-sports.io/players/topassists?season=2022&league=140"

            payload={}


            response = requests.request("GET", url, headers=headers, data=payload)
            
            data = response.json()['response']
            
            return render_template("assists.html", data=data)

        if request.form['submit_button'] == 'Bundesliga Playmakers':
            
            url = "https://v3.football.api-sports.io/players/topassists?season=2022&league=78"

fb_api/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="../static/CSS/main.css">
<title>FB API</title>
</head>
<body>
    
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">
            <img src="../static/images/soccerball.png" width="80" height="60" alt="">
          </a>
        <a class="navbar-brand" href="{{ url_for('site.home') }}">Football API</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('site.home') }}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('site.results') }}">Results</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('site.standings') }}">Standings</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('site.fixtures') }}">Fixtures</a>
                </li>
                {% if current_user.is_authenticated%}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('site.scorers') }}">Top Scorers</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('site.assists') }}">Playmakers</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('site.profile') }}">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('cont.contact') }}">Contact Us</a>
                </li>
                {% endif %}
                {% if not current_user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.signin') }}">Sign In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.signup') }}">Sign Up</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    {% block content %}
        
    {% endblock content %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

fb_api/templates/form.html
<div class="row">
    <div class="col-md-5 offset-4">
        <form method="POST">
            {{ form.hidden_tag() }}
            <div class="form-group">
                <fieldset>
                    {{ form.email.label }}
                    {{ form.email(class = "form-control", placeholder = "Enter email address") }}
        
                </fieldset>
                <fieldset>
                    {{ form.password.label }}
                    {{ form.password(class = "form-control", placeholder = "Enter password") }}
        
                </fieldset>
                {{ form.submit_button(class="btn btn-dark") }}
            </div>
        </form>
    </div>
</div>